# Generated by Django 4.1.7 on 2023-03-12 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchased_course',
            options={'verbose_name': 'Purchase course', 'verbose_name_plural': 'Purchased courses'},
        ),
        migrations.RemoveField(
            model_name='purchased_course',
            name='certificate_url',
        ),
        migrations.AlterField(
            model_name='purchased_course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
