# Generated by Django 4.1.7 on 2023-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_purchased_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_course',
            name='lessons_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
