# Generated by Django 4.1.7 on 2023-03-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_purchased_course_lessons_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchased_course',
            old_name='lessons_view_count',
            new_name='lessons_video_count',
        ),
        migrations.AddField(
            model_name='purchased_course',
            name='viewed_video_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
