# Generated by Django 4.1.7 on 2023-03-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qurilmalar Identifikatori'),
        ),
    ]
