# Generated by Django 4.1.7 on 2023-03-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_finished',
        ),
    ]
