# Generated by Django 4.1.7 on 2023-03-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='video_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
