# Generated by Django 4.1.7 on 2023-03-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courselesson_video_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCompletion',
        ),
    ]
