# Generated by Django 4.1.7 on 2023-03-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_coursecompletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.DeleteModel(
            name='VideoComment',
        ),
    ]
